### ISSUE TITLE
Support extracting terraform version from .tool-versions

### ISSUE THREAD

**Issue by tommybo-entur** [entur/gha-terraform#44]
When using asdf-vm we specify terraform version in .tool-versions. It would be nice if this action automatically detects and use this version if available.

Notice that for our use the versions file is located in repository root, but I've seen other teams putting it in subfolders (i.e. \<root\>/terraform).

**Comment by bvestli** [comment]
We had a discussion in team plattform about this and decided to close this issue. The reason is that we do not want to make asdf a tool used to set terraform version since it does not support parsing the version from `required_version` in the terraform code which is the correct way to specify which version of the Terraform CLI is allowed to run the configuration.

We will look more into good solutions if the outcome of the CD-pilot is to use GitHub for CD. But until we have made a decision about CD-tool we will leave this reusable workflow as-is.
